# Generated by Django 4.1.3 on 2022-11-19 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("number", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("hours_per_day", models.IntegerField()),
                ("totalhours", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.PositiveIntegerField()),
                ("student_fname", models.CharField(max_length=200)),
                ("student_lname", models.CharField(max_length=200)),
                ("student_email", models.CharField(max_length=200)),
                ("DOB", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("semester", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "course",
                    models.ManyToManyField(
                        blank=True,
                        related_name="semester_course",
                        to="attendance.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.PositiveIntegerField()),
                ("lecturer_fname", models.CharField(max_length=200)),
                ("lecturer_lname", models.CharField(max_length=200)),
                ("lecturer_email", models.CharField(max_length=200)),
                ("DOB", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollegeDay",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "Class",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collegeday_class",
                        to="attendance.class",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_course",
                to="attendance.course",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.lecturer",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.semester"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="student",
            field=models.ManyToManyField(
                related_name="class_student", to="attendance.student"
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("absent_hours", models.IntegerField()),
                ("attendance_rate", models.FloatField()),
                (
                    "classes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.class",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.student",
                    ),
                ),
            ],
        ),
    ]
